/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject6
 */
export interface InlineObject6 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject6
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject6
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject6
     */
    shared?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof InlineObject6
     */
    topics?: Array<number>;
}

export function InlineObject6FromJSON(json: any): InlineObject6 {
    return InlineObject6FromJSONTyped(json, false);
}

export function InlineObject6FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject6 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
        'topics': !exists(json, 'topics') ? undefined : json['topics'],
    };
}

export function InlineObject6ToJSON(value?: InlineObject6 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'comment': value.comment,
        'shared': value.shared,
        'topics': value.topics,
    };
}


