/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2008Authors
 */
export interface InlineResponse2008Authors {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2008Authors
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2008Authors
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2008Authors
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2008Authors
     */
    roleName: string;
}

export function InlineResponse2008AuthorsFromJSON(json: any): InlineResponse2008Authors {
    return InlineResponse2008AuthorsFromJSONTyped(json, false);
}

export function InlineResponse2008AuthorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2008Authors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'roleName': json['roleName'],
    };
}

export function InlineResponse2008AuthorsToJSON(value?: InlineResponse2008Authors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'roleName': value.roleName,
    };
}


