/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse20016Book
 */
export interface InlineResponse20016Book {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20016Book
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20016Book
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20016Book
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse20016Book
     */
    language?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse20016Book
     */
    timeRequired?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse20016Book
     */
    shared?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse20016Book
     */
    publishedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse20016Book
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse20016Book
     */
    updatedAt?: Date;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse20016Book
     */
    details?: object;
}

export function InlineResponse20016BookFromJSON(json: any): InlineResponse20016Book {
    return InlineResponse20016BookFromJSONTyped(json, false);
}

export function InlineResponse20016BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse20016Book {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'timeRequired': !exists(json, 'timeRequired') ? undefined : json['timeRequired'],
        'shared': !exists(json, 'shared') ? undefined : json['shared'],
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'details': !exists(json, 'details') ? undefined : json['details'],
    };
}

export function InlineResponse20016BookToJSON(value?: InlineResponse20016Book | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'language': value.language,
        'timeRequired': value.timeRequired,
        'shared': value.shared,
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'details': value.details,
    };
}


