/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2004Release,
    InlineResponse2004ReleaseFromJSON,
    InlineResponse2004ReleaseFromJSONTyped,
    InlineResponse2004ReleaseToJSON,
    InlineResponse2008Authors,
    InlineResponse2008AuthorsFromJSON,
    InlineResponse2008AuthorsFromJSONTyped,
    InlineResponse2008AuthorsToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2008Nodes
 */
export interface InlineResponse2008Nodes {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2008Nodes
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2008Nodes
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2008Nodes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2008Nodes
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2008Nodes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2008Nodes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<InlineResponse2008Authors>}
     * @memberof InlineResponse2008Nodes
     */
    authors?: Array<InlineResponse2008Authors>;
    /**
     * 
     * @type {InlineResponse2004Release}
     * @memberof InlineResponse2008Nodes
     */
    release?: InlineResponse2004Release;
}

export function InlineResponse2008NodesFromJSON(json: any): InlineResponse2008Nodes {
    return InlineResponse2008NodesFromJSONTyped(json, false);
}

export function InlineResponse2008NodesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2008Nodes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'authors': !exists(json, 'authors') ? undefined : ((json['authors'] as Array<any>).map(InlineResponse2008AuthorsFromJSON)),
        'release': !exists(json, 'release') ? undefined : InlineResponse2004ReleaseFromJSON(json['release']),
    };
}

export function InlineResponse2008NodesToJSON(value?: InlineResponse2008Nodes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'parentId': value.parentId,
        'name': value.name,
        'description': value.description,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'authors': value.authors === undefined ? undefined : ((value.authors as Array<any>).map(InlineResponse2008AuthorsToJSON)),
        'release': InlineResponse2004ReleaseToJSON(value.release),
    };
}


