/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject16
 */
export interface InlineObject16 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject16
     */
    memoContent?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineObject16
     */
    topicId?: number;
}

export function InlineObject16FromJSON(json: any): InlineObject16 {
    return InlineObject16FromJSONTyped(json, false);
}

export function InlineObject16FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject16 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'memoContent': !exists(json, 'memoContent') ? undefined : json['memoContent'],
        'topicId': !exists(json, 'topicId') ? undefined : json['topicId'],
    };
}

export function InlineObject16ToJSON(value?: InlineObject16 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'memoContent': value.memoContent,
        'topicId': value.topicId,
    };
}


