/* tslint:disable */
/* eslint-disable */
/**
 * chibichilo-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2009Releases,
    InlineResponse2009ReleasesFromJSON,
    InlineResponse2009ReleasesFromJSONTyped,
    InlineResponse2009ReleasesToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2009
 */
export interface InlineResponse2009 {
    /**
     * 
     * @type {Array<InlineResponse2009Releases>}
     * @memberof InlineResponse2009
     */
    releases?: Array<InlineResponse2009Releases>;
}

export function InlineResponse2009FromJSON(json: any): InlineResponse2009 {
    return InlineResponse2009FromJSONTyped(json, false);
}

export function InlineResponse2009FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2009 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'releases': !exists(json, 'releases') ? undefined : ((json['releases'] as Array<any>).map(InlineResponse2009ReleasesFromJSON)),
    };
}

export function InlineResponse2009ToJSON(value?: InlineResponse2009 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'releases': value.releases === undefined ? undefined : ((value.releases as Array<any>).map(InlineResponse2009ReleasesToJSON)),
    };
}


