name: build sphinx document
on: 
  push:
    branches:
      - 'docs'
    paths:
      - 'V2.1/Design/**'
      - 'V2.1/UserManual/**'
      - 'V2.1/OnBoarding/**'
      # build対象は、V2.1/Design/* と V2.1/UserManual/* V2.1/OnBoarding/* とする。
      # 個別 build への布石
jobs:
  main:
    name: build sphinx document
    runs-on: ubuntu-latest
    steps:
      # 自分の repository を checkout する。
      # 高速化は、ディフォルト値をあとで確認する。
      # --depth 1 だったはず?
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: docs
      # Identity を設定
      - name: set identity
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "bot"
      - name: Set up Ubuntu 20.04 environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          # 日本語が豆腐になるので、ipafont と ipaexfont を入れる。
          sudo apt install python3-sphinx python3-sphinx-rtd-theme python3-sphinxcontrib.plantuml python3-pip fonts-ipafont fonts-ipaexfont
          pip3 -V
      - name: build sphinx document
        run: |
          (cd  ./V2.1/;dash ./DocumentBuild.sh)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

