name: build
on: pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v4
        with:
          version: 11.1.2
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - name: install
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm run lint:fix:report
        continue-on-error: true
      - name: "commit lint:fix"
        run: |
          if git -c "user.name=bot" -c "user.email=bot@example" commit -am "bot: lint:fix"; then
            git push origin HEAD
          fi
      - uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ github.token }}"
          only-pr-files: false
      - name: format
        run: pnpm run format
      - name: "commit format"
        run: |
          if git -c "user.name=bot" -c "user.email=bot@example" commit -am "bot: format"; then
            git push origin HEAD
          fi
      - name: test
        run: pnpm test
      - name: build
        run: pnpm run build
